spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/valemais}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
    show-sql: ${FORMAT_AND_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_AND_SHOW_SQL:true}